In [46]:
import numpy
import statistics

# Lấy ma trận 1 chiều để test

In [55]:
age = numpy.array([3,56,23,39,156,52,41,22,9,28,139,31,55,20,-67,37,11,55,45,37])
print(age)

[  3  56  23  39 156  52  41  22   9  28 139  31  55  20 -67  37  11  55
  45  37]


# Kiểm tra, test thử ma trận chuyển vị python

In [54]:
A = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)
print("Transpose matrix")
print(numpy.transpose(A))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose matrix
[[1 4 7]
 [2 5 8]
 [3 6 9]]


# Tính ma trận chuyển vị của Age, mà thực ra ma trận 1 chiều, chuyển vị cũng như nhau

In [56]:
ageTranspose = numpy.transpose(age)
print(ageTranspose)


[  3  56  23  39 156  52  41  22   9  28 139  31  55  20 -67  37  11  55
  45  37]


# Tính số lượng sample (n)

In [58]:
n = len(age)
print(n)

20


# Tính giá trị trung bình

In [48]:
ageMean = statistics.mean(age)
print(ageMean)

39


# Thử công thức của thầy

In [63]:
xichMa = 0
for i in range(0,n):
    xichMa = xichMa + ((age[i]-ageMean)*(age[i]-ageMean).T)

covarianceMatrix = xichMa*(1/(n-1))
    

In [64]:
covarianceMatrix

2106.0

# Thử bằng hàm của python

In [65]:
print(f"Test with covariance matrix from numpy : {numpy.cov(age)}")

Test with covariance matrix from numpy : 2105.6210526315795
